#!/usr/bin/env bash

git fetch
git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} -- | xargs bundle exec rubocop | tee .rubocop_result

rubocop_exit_status="${PIPESTATUS[1]}"

cat .rubocop_result | reviewdog -f=rubocop -reporter=github-pr-review

exit "$rubocop_exit_status"
