name: lint

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']
        bundler-version: ['2.2.29']
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: gem install bundler -v ${{ matrix.bundler-version }}
      - run: bundle install
      - run: bash .github/scripts/run_rubocop
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
