name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rails

    env:
      RAILS_ENV: test
      RAILS_TEST_DATABASE_HOST: 0.0.0.0

    services:
      mysql_test:
        image: dockerdxm/r02_db:0.1
        ports:
          - '13306:3306'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install required gems
        run: |
          gem install bundler:2.0.1
          bundle install --jobs 4 --retry 3
      - name: Migrate DB
        run: bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
